#!/bin/bash

ENV_FILE="$HOME/.galadrielenv"
GALADRIEL_ENVIRONMENT="production"
GALADRIEL_MODEL_COMMIT_HASH="3aed33c3d2bfa212a137f6c855d79b5426862b24"

{
  echo "GALADRIEL_ENVIRONMENT=${GALADRIEL_ENVIRONMENT}"
  echo "GALADRIEL_API_URL=${GALADRIEL_API_URL}"
  echo "GALADRIEL_NODE_ID=${GALADRIEL_NODE_ID}"
  echo "GALADRIEL_RPC_URL=${GALADRIEL_RPC_URL}"
  echo "GALADRIEL_API_KEY=${GALADRIEL_API_KEY}"
  echo "GALADRIEL_MODEL_ID=${GALADRIEL_MODEL_ID}"
  echo "GALADRIEL_LLM_BASE_URL=${GALADRIEL_LLM_BASE_URL}"
  echo "GALADRIEL_MODEL_COMMIT_HASH=${GALADRIEL_MODEL_COMMIT_HASH}"
} > ${ENV_FILE}

# display the content of the file
# will be useful for debugging
cat ${ENV_FILE}