name: Lint MyPy & Pylint

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install Python Dependencies
        run: |
          pip install -e .
          pip install pylint==3.2.7
          pip install mypy==1.11.2
      - name: Run MyPy
        run: mypy .
      - name: Run PyLint
        run: pylint --rcfile=setup.cfg galadriel_node/*
