name: unit tests
on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install Python Dependencies
        run: |
          pip install -e .
          pip install pytest==8.3.2
          pip install pytest-mock==3.14.0
          pip install pytest-asyncio==0.24.0
      - name: Run tests
        run: python -m pytest tests
